### ISSUE TITLE
Syncthing-gtk only works with tagged releases

### ISSUE THREAD

**Issue by pstn** [syncthing/syncthing-gtk#133]
Everything that is not a tagged official release by syncthing (for example a git clone) reports it's version as "unknown-dev". syncthing-gtk refuses to work with these builds, but instead just prints out a dialogue that tells you to update to a recent version and quits. Maybe it would be better to just print a warning that the syncthing version is unknown and that things could break and continue to run instead.

**Comment by kozec** [comment]
Well...

1st, ST-GTK will _not_ work with dev version because of recent protocol changes, unless you are running v0.11 branch.
2nd, git clone of syncthing is build with version string like '_v0.11.0-beta5+17-g75fb14a_' what should be ST-GTK able to interpret.
And 3rd I can add special exception and let '_unknown-dev_' to be parsed as, lets say, version 1000.1. But that may and _will_ cause interesting number of problems :)
