### ISSUE TITLE
Move emblem icon location to theme-friendly location

### ISSUE THREAD

**Issue by allanbreyes** [syncthing/syncthing-gtk#177]
Makes it easier (and possible?) for themes like Numix to change Syncthing's emblem icons.

It's currently installing to `/usr/share/pixmaps` - I think, here: https://github.com/syncthing/syncthing-gtk/blob/cc14a0b4a4721459bc7715d7f8c4b7a31533adec/setup.py#L73

Other file sync'ing services like Dropbox, Insync, Ubuntu One use `/usr/share/icons/[THEME]/[SIZE]/emblems/`, e.g. `/usr/share/icons/hicolor/48x48/emblems/`

**Comment by kozec** [comment]
Sound's reasonable, I'll check what it will break :)

**Comment by kozec** [comment]
Well, it looks like icons in share/icons/hicolor/64x64/emblems are picked without problem, but override in ~/.icons/Mint-X-Dark/emblems/64x64 (theme I'm using) is happily ignored :( Icons are called by name in nautilus plugin, so that shouldn't be a problem.

Anyway, location problem should be fixed.
