### ISSUE TITLE
fedora packages not installable

### ISSUE THREAD

**Issue by FlorianLudwig** [syncthing/syncthing-gtk#207]
The rpm depends on /bin/python being provided.  On fedora the path is /usr/bin/python

**Comment by kozec** [comment]
```
[tom@localhost ~]$ ls -l /bin/python*
lrwxrwxrwx. 1 root root    7 Dec 11  2013 /bin/python -> python2
lrwxrwxrwx. 1 root root    9 Dec 11  2013 /bin/python2 -> python2.7
-rwxr-xr-x. 1 root root 6412 Nov 12  2013 /bin/python2.7
lrwxrwxrwx. 1 root root    9 Dec 11  2013 /bin/python3 -> python3.3
-rwxr-xr-x. 2 root root 6452 Nov  7  2013 /bin/python3.3
-rwxr-xr-x. 2 root root 6452 Nov  7  2013 /bin/python3.3m
-rwxr-xr-x. 1 root root 1194 Aug  4  2013 /bin/python3-mako-render

[tom@localhost ~]$ cat /etc/fedora-release 
Fedora release 20 (Heisenbug)

```

Some actual output would help.

**Comment by FlorianLudwig** [comment]
````
# dnf install syncthing-gtk
Error: nothing provides /bin/python needed by syncthing-gtk-0.7.6-10.1.i686

# cat /etc/fedora-release
Fedora release 22 (Twenty Two)
```

**Comment by FlorianLudwig** [comment]
there is a /bin/python because:
```
# ls -lah /
lrwxrwxrwx    1 root root    7 16. Aug 2014  bin -> usr/bin
```

but the package manager does not recognize this as the python package only provides /usr/bin/python

**Comment by kozec** [comment]
Just as statusreport, since I don't actually have any idea wtf is going on...

Funny part is that ST-GTK nor spec file for it doesn't include any reference to /bin/python. That path and requirement is added by rpmbuild. And then refused by that thing which replaced yum. [This dnf bug is probably related](https://bugzilla.redhat.com/show_bug.cgi?id=1005235). I'm currently trying to find way how to prevent that, but so far it looks like any reference to any package that even remotely looks like it may need python adds /bin/python requirement :D

**Comment by kozec** [comment]
Soo... At least until I find way how to make Fedora and OBS behave together (or until I'll learn how copr works), "official" source fedora packages is changed to [decathorpe's copr repository](https://copr.fedoraproject.org/coprs/decathorpe/syncthing/).
