### ISSUE TITLE
Add the possibility to start daemon with nice and ionice

### ISSUE THREAD

**Issue by acidicX** [syncthing/syncthing-gtk#227]
It would be cool if ST-GTK could start the syncthing deamon with nice and ionice parameters, like this:

````nice -n 19 ionice -c 2 -n 7 syncthing````

This could also be done in the Settings/Advanced tab, but the executable field won't accept spaces.

**Comment by kozec** [comment]
Yes, that sounds easy enough. I'll check what can be done.

**Comment by kozec** [comment]
@acidicX  Just quick question, is scheduling class (-c parameter) enough? Because adding 2nd combobox or all possible -c -p combinations may end looks messy.

**Comment by acidicX** [comment]
I'd just change the text field so it accepts a string for calling the daemon, then everyone can go as wild as they want?
-c is not enough though, in my mind...

**Comment by kozec** [comment]
So, that another option :)

I have text field [in this branch](https://github.com/syncthing/syncthing-gtk/tree/commandline)  ( [image, if you don't feel like running stuff from git](http://pasteboard.co/VKHxEsX.png) ), but there is one problem with this approach.
User can write something stupid there and ST-GTK ends in infinite loop of failed start attempts. I'll need to do little settings dialog rework, because there is currently no way how to access it before Syncthing daemon is started.

**Comment by acidicX** [comment]
:+1: looks good to me! Thank you!
