### ISSUE TITLE
Just updated and now Synthing-GTK borked (on Linux Mint)

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing-gtk#269]
What happened: I updated Syncthing - I _think_ it was Syncthing itself rather than the GUI a.k.a. Syncthing-GTK; then I had a 'folder conflict', which I seem to have resolved; and yet now the GUI seems broken. [Screenshot here.](http://imgur.com/TCNY0oM) (Ignore the red - that's where I've redacted my computer name.)

Notice the missing folder pane and also how much - even the 'ok' and 'cancel' buttons in the foremost window - is greyed out.

All seems well in the web interface, though.

Syncthing (GTK) v0.8.3 (Daemon v0.13.0)
Linux Mint 17.3 x64. Kernel x86_64 Linux 4.2.0-36-generic.

**Comment by eugenesan** [comment]
@ACinnamonUserInUK Syncthing-GTK 0.9+ is required for Syncthing 0.13.
Please give the developers some time to make required adaptations.

**Comment by ACinnamonUserInUK** [comment]
eugenesan: thanks. Sorry if I was blunt. I was a bit thrown when things suddenly stopped working. However, the web UI does still work, so that's OK.

**Comment by eugenesan** [comment]
@ACinnamonUserInUK I can't speak for the developers but since this update is indeed "bumpy" (due to quite some changes in Syncthing daemon) your report seems adequate.

Developers are already working on fixes and I hope the issues will be resolved shortly.
Please follow https://github.com/syncthing/syncthing-gtk/issues/267 to monitor the progress.
