### ISSUE TITLE
Syncthing-GTK exits after Windows wakes from sleep

### ISSUE THREAD

**Issue by T3RM1NU5** [syncthing/syncthing-gtk#293]
I am currently using Syncthing-GTK on Windows 10.  When my Windows 10 laptop wakes from sleep syncthing-gtk displays two errors.  

The first one 

> Connection to daemon failed. Check your configuration and try again.
> Error message: Error receiving data: An existing connection was forcibly closed by the remote host.
> Close

Second one

> Connection to Syncthing daemon lost. Syncthing is probably restarting or has been shutdown
> Quit

however the daemon continues to run in the background until I close the error boxes.  
Once I press cancel or close the daemon stops  and the syncthing-gtk application closes.

**Comment by kozec** [comment]
That's rather weird, that error message should go away once connection is redone.

Can you access WebUI while this happening?
(and does same thing happens for someone with Windows 7?)

**Comment by T3RM1NU5** [comment]
@kozec 
> Can you access WebUI while this happening?
Yes, I can continue to access the webui until I try and close the error dialog boxes

**Comment by kozec** [comment]
> dialog boxes

I realized only now, are you saying that BOTH dialogs are shown at once?

I'd probably have to get Windows notebook and replicate it. Does it happens every time, randomly or, for example, only if PC is sleeping for some time?

**Comment by acolomb** [comment]
I just experienced a similar problem on Windows 7. Probably it was related to Syncthing being auto-updated from v0.14.0 to v0.14.2 this morning. After or during the upgrade (can't tell exactly, it happened while logging in and ST-GTK was autostarted), it displayed

> Syncthing daemon is being updated

 and the first message @T3RM1NU5 reported:

> Connection to daemon failed. Check your configuration and try again.
> Error message: Error receiving data: An existing connection was forcibly closed by the remote host.
> Close

both at once.

Closing the second message window led to ST-GTK quitting completely. Unfortunately I did not check whether the WebUI was available. Could it be related to the "forcibly closed by remote host" condition? Does ST-GTK behave distinguish between different socket errors when the connection was lost?

**Comment by T3RM1NU5** [comment]
It does not happen every time.  It happens every other time or so after the
computer has been a sleep for several minutes.

**Comment by T3RM1NU5** [comment]
I should have submitted this sooner, but I ran the the binary from the console and captured a traceback from when it crashed.

```
> syncthing-gtk-console.exe
I StatusIcon    Using backend StatusIconGTK3 (primary)
I App
I App           Syncthing-GTK started and running in notification area
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 409, in _rest_connected
Error: g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
I App           updatecheck: too soon
I App           updatecheck: too soon
I App           updatecheck: too soon
I App           updatecheck: too soon
I App           updatecheck: too soon
I App           updatecheck: too soon
I App           updatecheck: too soon
I App           updatecheck: too soon
I App           Checking for updates...
E StDownloader  g-io-error-quark: GET request failed: WinHttp error: NAME_NOT_RESOLVED (0)
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\stdownloader.py", line 135, in _cb_read_compatibility
Error: g-io-error-quark: GET request failed: WinHttp error: NAME_NOT_RESOLVED (0)
W Daemon        Daemon instance was replaced unexpedtedly. Disconnecting from daemon.

```

**Comment by rongmu** [comment]
I am running Syncthing-GTK on Windows 7 and have encountered similar problems.

This is the error window displayed after resuming from sleep:

![resume from sleep](http://i.imgur.com/RZAbC7A.png)

An error also occurs when I am logging off or shutting down my computer:

![logoff / shutdown](http://i.imgur.com/2FiSyay.png)

Currently, I work around this issue by starting the syncthing daemon via Windows Task Scheduler.

**Comment by kozec** [comment]
Frankly, at this point, I'm pretty-much waiting for miracle in shape of someone who knows what Windows does when going in and out of sleep mode.

As of now, I can't
a) replicate this at all
b) see any connection between sleep mode and anything. ST-GTK has no code related to it and it shouldn't even "know" about machine entering it :(

**Comment by WarmChocolateCake** [comment]
I've been seeing this for a while now and just thought it might be me ;)

I'm seeing this on a laptop with wifi ... the laptop also has an (unused) LAN connection and several VM NICs (both VMware and Virtualbox)...

I'm using Windows 7 64-bit... I'm also using Syncthing & Syncthing-GTK on 2x Arch Linux computers and a Debian based NAS (OpenMediaVault with the Syncthing plugin)...

Syncthing-GTK version is `v0.9.2.2-3-gf055b5c-win32`

Personally, I think that this is something to do with Windows and the TCP/IP stack getting all reset after a suspend / hibernation... hence thinking that this was just me due to my excessive hoarding of NICs ;)

I've seen the fail with just the "Close" dialog box and both the "Close" and "Quit" dialog boxes open...

Picking up on the comment by @rongmu - I sometimes see that error when shutting down and sometimes I even see a small dialog asking for the location of the syncthing binary location... soo... something's dying in a weird way during shutdown... (but that's less important for me) - and I'm guessing it should be a separate bug report ;)

I've run syncthing-gtk-console.exe and watched the output after several suspends / resumes, but I agree - it's hard to pin this one down... leaving the laptop off overnight didn't seem to produce a failure, but popping out for an hour this morning and returning.. bam... failure.

The difference (in this case) between the (all ok) overnight suspend and the (failure) 1 hour suspend, was that the Syncthing-GTK window was closed when it failed (the syncthing-gtk-console.exe command line window was still open)... in previous tests, I even had the Daemon Output window showing, hoping to catch the error...

All I saw in the command line window at the point of failure was:
`W Daemon        Daemon instance was replaced unexpedtedly. Disconnecting from daemon.`

But that's appeared before...
`W Daemon        Daemon instance was replaced unexpedtedly. Disconnecting from daemon.
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 413, in _rest_connected
Error: g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 413, in _rest_connected
Error: g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
I App           Checking for updates...
I StDownloader  Not using latest, unsupported Syncthing version v0.14.9; Using v0.14.4 instead
I App           Updatecheck: needs_upgrade = False`

So, in my single observation here, Syncthing-GTK is noticing that there is a disconnection, but in some cases it isn't able to reinstantiate it...

I'd like to log the output of syncthing, but I can't seem to find the correct syntax in the UI settings / Advanced tab... 

I currently have:
`STTRACE="all" -verbose -logflags=3`

But if I try to put `-logfile=c:\temp\syncthing.log` or  `-logfile="c:\temp\syncthing.log"`, I don't get a log... is Syncthing-GTK stealing the output (ie  `-logfile="-"`) for the Daemon Output window?? Can I override that somehow?

This is Windows, so I don't have "logger" as per the Linux example on that UI Settings tab...

Actually, I think I need to have `-logfile="c:\temp\syncthing(%time%).log"`, otherwise restarting the daemon would overwrite the log...

Anyway, if you could give me a way to getting better logging out of syncthing and maybe add timestamps to the syncthing-gtk-console output, then I'm sure I can help to replicate this... it's happening ~2 a day... (obviously it depends on how often I let the laptop sleep)

Just to add another comment that might just be "noise"... 
Because of this failure, I run syncthing on it's own sometimes... so it's upgraded itself. So, in the syncthing-gtk-console output, I'm seeing:
`I StDownloader  Not using latest, unsupported Syncthing version v0.14.9; Using v0.14.4 instead`
I see something the older version appear in %TEMP%, yet as far as I can tell, the daemon is still running the newer version (`v0.14.9`) in this case - so could it be that the failures are due to Syncthing-GTK trying to run a different version and losing track of which one is actually running? 

Like I said, that might be noise... I need to look a little closer at the logs...

**Comment by DerGary** [comment]
I have the same issue than @T3RM1NU5. I'm also on Windows 10 and I updated from an older Version of Syncthing and Syncthing-GTK to the latest versions and now I'm getting the same behavior. Unfortunately I don't know which version of Syncthing and ST-GTK I had installed previously but it was working without any problems.

I would be happy to provide any logs if that would help to fix this issue.

Greetings Gary

**Comment by seiferflo** [comment]
Hi Same problem on W10 & W7 computers. I also never reported it thinking it was related to my setup. It happens in similar conditions as described above by T3RM1NU5 & WarmChocolateCake. I can also replicate this easily providing logs are useful to you.

**Comment by WarmChocolateCake** [comment]
Just whilst I'm logged in, thought I'd just mention that this issue is still here for me... maybe worth mentioning that if I look at syncthing's webgui, it's still running, so I'm 99% sure that there's something happening with syncthing restarting after a sleep/wake detection and syncthing-gtk losing it's grip on the original syncthing process...

**Comment by kozec** [comment]
This should be fixed with latest release.
