### ISSUE TITLE
[Feature] Force UI Language

### ISSUE THREAD

**Issue by vladipus** [syncthing/syncthing-gtk#301]
Would like to have an ability to choose explicitly the UI language.

Thank you for your project!

**Comment by kozec** [comment]
`LANGUAGE=sk_SK.UTF-8 syncthing-gtk`  :)

**Comment by vladipus** [comment]
Will this work on MS Windows? A GUI solution would be nicer ^_^

**Comment by kozec** [comment]
Yes, it should, although language code is only two letter ([gray part here](https://github.com/syncthing/syncthing-gtk/tree/master/locale))

About GUI, I'm not sure if it's possible, because that's something that has to be set *before* ST-GTK starts, otherwise you may end with half-translated UI. But I'll check if there is any way to worakound it.

**Comment by vladipus** [comment]
"Please, restart for changes to take effect." is fine!
