### ISSUE TITLE
Notification message is not displayed correctly (fra)

### ISSUE THREAD

**Issue by incyclum** [syncthing/syncthing-gtk#324]
![capture d ecran de 2016-09-26 22-11-07](https://cloud.githubusercontent.com/assets/7466095/18850172/a9430976-8436-11e6-8fc9-5a0b4cfc2d5c.png)

As you can see in the screenshot, you read `'set([u'Wallpapers'])'` instead of `'Wallpapers'`.

Using Syncthing-GTK 0.9.2.2 with Gnome 3.20.2

**Comment by kozec** [comment]
I'm sorry, this is probably related to #315, but would you kindly translate that message?

**Comment by incyclum** [comment]
Yes, it is related to #315, `Synchronization of folder 'Wallpaper' is completed`.

**Comment by kozec** [comment]
found it 8-)

**Comment by acolomb** [comment]
Wow, I don't know enough python to even understand the difference :-(

Really strange syntax that is...

**Comment by kozec** [comment]
> Wow, I don't know enough python to even understand the difference :-(

You should probably say that BEFORE I accepted you pull request :D

{ stuff, without, any, colon  }  is syntax for set, { key : value } is for dict. Luckily, python has only few of those.

**Comment by incyclum** [comment]
Thanks guys :)

**Comment by acolomb** [comment]
Thanks for the python lesson. Yes, I probably should have said I'm a python noob. I did say that it was untested, though ;-)

Somewhere I had seen the syntax with curly braces in a similar context, so I copied it. Still don't know what the trailing comma does. That's really weird syntax.

**Comment by kozec** [comment]
> Still don't know what the trailing comma does. That's really weird syntax.

Ensures it's tuple. ( ) with  just one element is parsed as expression in parentheses otherwise.

In this specific case it's probably not needed, but I got accustomed to writing it like that, because passing random stuff to string "%" operator may break if value after % is iterable and has more than expected number of items inside. Writing (something,) ensures that "%" will look at tuple with single item.
