### ISSUE TITLE
GLib-ERROR **: Creating pipes for GWakeup: Too many open files

### ISSUE THREAD

**Issue by jtojnar** [syncthing/syncthing-gtk#344]
Yesterday, I managed to synchronize around 18 GB of data until Syncthing crashed due to lack of space. I freed some capacity but Syncthing-GTK always crashes shortly after start.

```
...
E Daemon        (GLib.Error('Unable to create socket: Too many open files', 'g-io-error-quark', 31), u'db/scan?folder=1oz7d-pg6ho&sub=School%2Fsem4%2Fplin%2Fnltk_data%2Fcorpora%2Fmovie_reviews%2Fneg%2F.syncthing.cv643_29282.txt.tmp', {}, u'1oz7d-pg6ho')
E Daemon        (GLib.Error('Unable to create socket: Too many open files', 'g-io-error-quark', 31), u'db/scan?folder=1oz7d-pg6ho&sub=School%2Fsem4%2Fplin%2Fnltk_data%2Fcorpora%2Fmovie_reviews%2Fneg%2Fcv643_29282.txt', {}, u'1oz7d-pg6ho')

(syncthing-gtk:25412): GLib-ERROR **: Creating pipes for GWakeup: Too many open files

[1]    25412 trace trap (core dumped)  syncthing-gtk
```

Using Ubuntu 16.10, Syncthing 0.14.16, Syncthing-GTK 0.9.2.3.

**Comment by kozec** [comment]
"Too many open files" means you ran into your ulimit, what's not really solvable in ST-GTK side. But if you were out of disk space when problem occured, there is good chance that limit was hit because of ST-GTK trying to restart Syncthing too many times, so simplest solution is to free some space and reboot - it should never happen again.

Also, is your avatar from Kanon? :)

**Comment by jtojnar** [comment]
Uguu, I would expect more graceful error handling; for example, Dropbox explicitly mentions inotify
 limit. I would not suspect that the watches are not freed when the app crashes, after reboot it indeed seems to be okay.

Ayu greets you.

**Comment by kozec** [comment]
> Uguu, I would expect more graceful error handling; for example, Dropbox explicitly mentions inotify
limit.

Yes, ST-GTK displays error in such case too, but what happened there is not inotify limit. Having no more fd's left is similar to having no memory - it's hard to display any kind of message, because you can't load data required to draw it.

That's why are those errors generated deep in GTK and "handled" immediately, without reporting to application.
