### ISSUE TITLE
Provide Syncthing-GTK AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [syncthing/syncthing-gtk#350]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Users would not have to rely on third-party packages or repositories, but could get the most recent version for Linux from the official download page (like for Windows and macOS)
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

Here is a __sample Syncthing-GTK AppImage for testing__:
https://bintray.com/probono/AppImages/Syncthing_GTK/_latestVersion#files

Here is the file used to control the deb to AppImage conversion:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/Syncthing-GTK.yml

This is expected to run on most 2014-ish and later distributions, although some fine-tuning may be necessary. It has been generated from the existing trusty ppa. if this project was using Travis CI to do continuous builds, we could bundle those up as AppImages as well.

Do you think this would be useful?
I'd be happy to help producing an official Syncthing-GTK AppImage.

**Comment by kozec** [comment]
I like the idea, but I know really nothing about AppImage, so I have two questions:

- Any sandboxing? Would ST-GTK be able to run Syncthing with write access to user folders? There is no much sense in synchronization tool in sandboxed environment :)
- `file Syncthing_GTK-0.9.2.4.glibc2.15-x86_64.AppImage` reports ELF 64-bit LSB executable, what about 32 bit distros? I mean, ST-GTK is python-based, it should theoretically run on toaster :)

And, well, it doesn't really work...

```
./Syncthing_GTK-0.9.2.4.glibc2.15-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_EeSTsI/usr/bin/syncthing-gtk", line 2, in <module>
    import sys, os, signal, gi
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib/python3.5/site-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so: undefined symbol: g_irepository_get_immediate_dependencies
```

I'm not sure how important is actual error message, as it clearly uses wrong python interpreter.
I'm on Manjaro which inherited Arch Linux's screwup #_1, `python` points to python3 instead of 2 as everywhere else.

**Comment by probonopd** [comment]
Hi @kozec 

> Any sandboxing?

There is no mandatory sandboxing with AppImage, although users can use e.g., [Firejail](https://github.com/netblue30/firejail) if they want to run an AppImage in a sandbox.

> what about 32 bit distros

One could also make AppImages for those, and for ARM, etc.

> g_irepository_get_immediate_dependencies

Most likely still a bug of the AppImage. I quickly tested it on *buntu but not on Arch so far. Python and its libraries come bundled inside the AppImage, so it _should_ work if done properly, I can look into fixing this if there is interest in general.

**Comment by interval1066** [comment]
No, this is not simply a bug of "App" whatever that is. There's something more fundamentally wrong here with gi... I'm here doing a search from a problem that's crept into several different desktop applications i rely on; the problem showed up after I installed something that required python 3, I believe. The problem is clearly with the 64 bit version of the main gi shared lib or the calling app that rely on it:

ImportError: /usr/lib/python2.7/dist-packages/gi/_gi.x86_64-linux-gnu.so: undefined symbol: g_irepository_get_immediate_dependencies

Simply importing gi into the python interpreter produces that msg. Now a bunch of bluetooth apps I use are broken. I hope this can be fixed soon. I suspect that re-installing min 18.1 would fix this, but that will be a huge pain in the ass.

**Comment by kozec** [comment]
It took only little more than year and AppImage is now provided along with release :)

**Comment by probonopd** [comment]
Thanks for providing the AppImage. However, it does not bundle all required components which cannot be expected to be part of each target systems (read: Python with all its needed modules):

![screenshot_2018-02-18_10-59-38](https://user-images.githubusercontent.com/2480569/36350572-f143dfa2-149a-11e8-944f-38d2bcfbd0e2.png)

An AppImage is supposed to run on each target system without the need for installation of additional software by the user.

**Comment by probonopd** [comment]
Here is an example of an AppImage that bundles Python and python-gobject:
https://bintray.com/probono/AppImages/Pronterface#files

It was built using https://github.com/AppImage/AppImages/blob/master/recipes/Pronterface.yml.

To do something like this by hand: https://github.com/AppImage/AppImages/blob/master/legacy/pythongtk3hello/Recipe

**Comment by kozec** [comment]
> Their dependencies must be bundled (unless they can reasonably be expected to come as part of the default installation of each target system)

ST-GTK depends on gi and GTK and bundling all of that will create crazily huge package. That's why I used [dependency check](https://github.com/syncthing/syncthing-gtk/blob/master/scripts/appimage-AppRun.sh#L27) with that message.

But now when I think of that, not bundling bcrypt and dateutil is stupid idea and I'll fix it, but GTK, python and gi are something that I expect to be part of default installation of each target system.

**Comment by probonopd** [comment]
I am running Xubuntu 16.04.

**Comment by kozec** [comment]
Thanks, I'll check what it does there. I updated release with package that bundles all python deps in meantime.

**Comment by kozec** [comment]
By the way, what's used to build recipe you've linked? It looks very debian-specific.

**Comment by probonopd** [comment]
https://github.com/AppImage/AppImages/blob/master/pkg2appimage is used on Ubuntu 14.04 (trusty) running on [Travis CI](https://travis-ci.org/) in my case, but most deb-based systems should do.
