### ISSUE TITLE
Proposal: Attach to multiple syncthing daemons

### ISSUE THREAD

**Issue by funkyfuture** [syncthing/syncthing-gtk#354]
it would be great if one could attach the gui to various daemons on different host. even better if one could switch between them in a single gui instance.

**Comment by kozec** [comment]
Sorry, but after playing with this idea a little, I think that this is simply too big change to just throw in. Most of code can survive having multiple daemon instances in same process, but stuff like notifications, updates and restarting would basically need complete rework.

So, I'm open for pull requests, but otherwise, this is not planned in any forseeable future :)
