### ISSUE TITLE
Syncthing-gtk crashing suddenly on ubuntu 16.04

### ISSUE THREAD

**Issue by popcorn9499** [syncthing/syncthing-gtk#355]
I have been having problems with syncthing along with syncthing-gtk continuously crashing on me. It seems to happen more so when stuff is syncronizing and i would look at its logs but idk where they are. I looked at the system log which had some information that was relavent to the time it crashed. 

`Feb 11 09:33:17 popcorn9499-gamer kernel: [119834.297702] traps: syncthing-gtk[20227] trap int3 ip:7fe4a481ea5b sp:7ffcc83fc770 error:0

Feb 11 09:41:32 popcorn9499-gamer kernel: [120329.299654] traps: syncthing-gtk[21220] trap int3 ip:7f69fc21ea5b sp:7fffced613d0 error:0
`

The kernal log told me the same thing. 

`Feb 11 09:30:54 popcorn9499-gamer kernel: [119691.295884] traps: syncthing-gtk[2876] trap int3 ip:7fbef4676a5b sp:7ffd604d20f0 error:0

Feb 11 09:33:17 popcorn9499-gamer kernel: [119834.297702] traps: syncthing-gtk[20227] trap int3 ip:7fe4a481ea5b sp:7ffcc83fc770 error:0

Feb 11 09:41:32 popcorn9499-gamer kernel: [120329.299654] traps: syncthing-gtk[21220] trap int3 ip:7f69fc21ea5b sp:7fffced613d0 error:0
`

I'm unsure what it is and if you need more information ill gladly answer some questions.
I will however give you the versions of the software that seems relevant.

Versions:
ubuntu 16.04
syncthing 
syncthing-gtk 0.9.2.3 (Daemon v0.14.23)
plasma 5.9.1

Thanks for reading hopefully we can resolve this issue

**Comment by kozec** [comment]
Try running it from console with `syncthing-gtk -d`, that way you'll get error message(s) before crash.

**Comment by popcorn9499** [comment]
`(syncthing-gtk:20760): GLib-ERROR **: Creating pipes for GWakeup: Too many open files
`

That was the error i got would i just have to increase my inotify limit? 

Sorry for the delayed response life got  busy this week. I hope this result helps fix the issue though

**Comment by kozec** [comment]
That sounds similar to #344 Problem is that this is most likely _not_ problem in ST-GTK itself, it's just way how your ulimits are configured. Try increasing that limits if possible and see if it helps.

**Comment by RKBK** [comment]
This just happened to me too. 

In my case, I had a computer that had been out of sync for a while, and I had installed the elfeed database in emacs on the computers that were in sync. This RSS reader database stores every entry (?) as a file on disk, so this database probably contains thousands of files. On my two other computers, I'm using either the cmd line syncthing or QSyncthingtray, neither of which apparently have issues with having too many files open. Is there any way that syncthing-gtk would be able to handle this situation, or is this just something that is out of control due to ulimits?

For now it seems I can just restart syncthing-gtk repeatedly until all the files sync (my computer won't allow me to do anything higher than "ulimit -n 10000").

**Comment by kozec** [comment]
> Is there any way that syncthing-gtk would be able to handle this situation, or is this just something that is out of control due to ulimits?

I'm afraid not, because this crash is generated in glib and I don't have too much options how to prevent it.

Just to be sure, @calmh, is there any chance that syncthing will keep opening files until overall ulimit is hit? Because in that case, I'm kinda surprised that ST-GTK is only thing crashing around...

**Comment by calmh** [comment]
It *shouldn't* and I haven't seen any reports about it. It will keep files open in the low hundreds or so though. I'd have to check the code to make sure of the numbers, but I think the database layer may keep up to like 64 or so files open, then files that are being synced (which is essentially the number of pullers, so 16 or something, times two if there is an old version of the file we are copying data from) plus any files being served because other nodes are asking for them - but those are opened/read/closed quickly so don't stay open for long.

**Comment by calmh** [comment]
From the perspective of syncthing-gtk, another possibility might be REST connections accumulating for some reason - for example if it does them often, they stick around due to HTTP keepalive, but don't actually get reused for whatever reason. I've done that often enough myself in other projects. :)

**Comment by kozec** [comment]
Yes, I though about that, but in that case, it would be crashing all the time, not just when syncthing downloads lot of files.

Anyway, I'm generating and synchronizing 100.000 files in loop and it holds so far :(

**Comment by calmh** [comment]
I guess one thing that might differ is that downloading lots of files generates lots of events which might generate lots of http connections.

**Comment by RKBK** [comment]
A detail that perhaps is important is that I'm using syncthing-inotify on all three computers. 

Does that keep opening files somehow? In a way that not using it would not be, causing issues with glib beyond what would happen if you were using using syncthing without syncthing-inotify?

**Comment by argv-minus-one** [comment]
As of aacc82e, this seems to happen if “monitor filesystem for changes” is turned on. Turning that feature off solves the problem.

Terminal output from a dying syncthing-gtk has lots of messages like this:

	E Daemon        (GLib.Error('Unable to create socket: Too many open files', 'g-io-error-quark', 31), u'db/scan?folder=Music&sub=Square%2FFinal%20Fantasy%20V%2Fff5-1-18.spc.ogg', {}, u'Music')

**Comment by kozec** [comment]
Ok, that makes lot of sense, especially it explains why it happens seemingly randomly.

inotify opens file handle for every directory it watches, recursively. So if directory structure is complicated enough, it _can_, in theory, easily eat that 1024 handles allowed by default.

... what sadly, yet again, points to your ulimit being too low.

But if those errors are displayed, ST-GTK should be able to catch situation _before_ crash and disable inotify on the fly, with some good looking critical error message. It's not ideal, but better than crashing...

**Comment by argv-minus-one** [comment]
Inotify should only use one file handle, not one per folder being monitored. (That was one of the problems with the dnotify API that inotify replaced.) Inotify watches are a separate, per-user limit, configured in `/proc/sys/fs/inotify/max_user_watches` (which defaults to 8192, but is 65536 on my system).

This crash only happened to me when syncthing was initially pulling a large folder (containing 8663 files and subfolders). The crash didn't happen when syncthing was merely monitoring the folder.

From the error messages I saw, it seems more like syncthing-gtk is trying to open a new socket to syncthing's HTTP server for every single file being received, and running out of file handles that way.
