### ISSUE TITLE
Being minimized when start with system booting

### ISSUE THREAD

**Issue by perqin** [syncthing/syncthing-gtk#373]
Though both of `Start Syncthing-GTK when I login to my desktop` and `Minimize to tray on start` are enabled, the GUI shows up when I login to the desktop environment. Is it the intended behavior? If so, please consider allowing the GUI not showing up at startup. I'm using Synching-gtk on Arch Linux + LxQt.

**Comment by kozec** [comment]
Nope, this is not intended, it should work as you expecting it.

But usually when this happens, it's caused by ST-GTK being started twice, most likely because of two entries in autostarted applications list. Can you check if that's not the case?

Other possible reason may be that tray icon area starts _after_ ST-GTK. If that's the case, adding small delay before ST-GTK is started may help.

**Comment by perqin** [comment]
@kozec I edited `~/.config/autostart/Syncthing-GTK.desktop` and change `Exec` to:
```
Exec=sleep 3 && /usr/bin/syncthing-gtk
```
But now it disappeared from systray until I open it manually from applications menu.
I also checked `~/.config/autostart` and there is only one `Syncthing-GTK.desktop`, so it should not start twice.

**Comment by kozec** [comment]
> But now it disappeared from systray until I open it manually from applications menu.

So, it starts like it is supposed to, but tray icon is not visible?

**Comment by perqin** [comment]
@kozec I checked again and unfortunately, no. After adding `sleep 3 && ` the tray icon is not visible, and with `ps aux | grep syncthing` I found that there is only syncthing backend running...... It is really strange that the GUI will not start.
