### ISSUE TITLE
Cannot find syncthing-plugin-*.py

### ISSUE THREAD

**Issue by bbaserdem** [syncthing/syncthing-gtk#439]
I am using version 0.9.3, from arch community. I have nemo and nemo-python packages installed.

When I run `syncthing-gtk -d` I found the following when I enter UI settings;

`W UISettingsDialog Cannot find syncthing-plugin-nemo.py required to support Nemo`

However, I do have the scripts at `/usr/share/<nemo/nautilus/caja>-python/extensions/` Is this a problem of searching directory on syncthing-gtk?

**Comment by kozec** [comment]
> However, I do have the scripts at /usr/share/<nemo/nautilus/caja>-python/extensions/ Is this a problem of searching directory on syncthing-gtk?

No, that sounds like problem of misplacing those files. File should be located in `/usr/share/syncthing-gtk/syncthing-plugin-nemo.py`. Enabling and disabling integration works by linking/removing that file into `~/.local/share/nemo-python/extensions`. If it is located in `/usr/share/nemo-python`, it is basically always enabled.

**Comment by getkey** [comment]
I encountered the issue with Nemo. `sudo mv /usr/share/nemo-python/extensions/syncthing-plugin-nemo.py /usr/share/syncthing-gtk/syncthing-plugin-nemo.py` did it for me. :wink:

These files have been [packaged there intentionally](https://bugs.archlinux.org/task/57123) in [this commit](https://git.archlinux.org/svntogit/community.git/commit/trunk/PKGBUILD?h=packages/syncthing-gtk&id=d4a7bbfcd69501fb3ad51c3c53c9dddee1d7836d). Maybe the fix is for Nautilus only, not Nemo? Ping @City-busz
