### ISSUE TITLE
cannot set folder to sendreceive, keeps going back to receiveonly

### ISSUE THREAD

**Issue by japhir** [syncthing/syncthing-gtk#493]
Trying to create a new folder on Arch Linux desktop BTRFS filesystem with the gtk gui. When everything is configured, and I open the options again (RMB, edit) the "Receive Only Folder" is toggled again, even though I've just turned it off.
When I manually edit the line in `~/.config/syncthing/config.xml` from `receiveonly` to `sendreceive`, it switches back on the next syncthing-gtk launch. Not fully sure if this issue belongs here or in syncthing/syncthing.

**Comment by mctome** [comment]
I also had the same problem, and I have the feeling that the problem is with syncthing-gtk.

Actually, when you use syncthing-gtk it doesn't matter whether you tick "send only", "receive only" (BTW there's a typo in there), or untick both, when you save and re-open the config tab, "receive only" will be selected.

I managed to fix the folder type back to "send & receive" by accessing the web interface (localhost:8384) in the affected machine, hope that workaround helps for now.

**Comment by Wrexthor** [comment]
Having the same problem in flatpak release of syncthing-gtk

**Comment by kozec** [comment]
This is same issue as #484, which is already fixed and released (since ~10 minutes ago :)

As for Flatpak, that's handled by someone at Flathub.
