### ISSUE TITLE
AppImage does not work on Fedora 31, and neither does the last provided dnf repo

### ISSUE THREAD

**Issue by zipy124** [syncthing/syncthing-gtk#551]
The appimage fails due to 
`** (process:26936): WARNING **: 16:29:01.965: Failed to load shared library 'libgdk_pixbuf-2.0.so.0' referenced by the typelib: libjpeg.so.8: cannot open shared object file: No such file or directory`

The dnf fails since nothing provides python-gobject or python-pyinotify.

**Comment by decathorpe** [comment]
@zipy124 (Maintainer of the former fedora package for syncthing-gtk speaking. Sorry you're having issues with this package on fedora.)

fedora (and most other distributions) have been getting rid of python 2 for the past few years, and right now, the necessary python2 libraries just aren't there anymore on fedora 31 and later - which is why I've removed the syncthing-gtk package as well, about half a year ago. The old RPM package (from fedora 30 or older) is just not supported anymore.

So, until syncthing-gtk is ported to python3 (which might as well never happen, according to some comments on issues in this project), it won't be reintroduced to fedora. You could try the flatpak version from flathub, if you really need it.

**Comment by zipy124** [comment]
Okay thank you I did suspect it might be an issue with the removal of python 2. Thank you for confirming this, its sad to see it stop working.
