### ISSUE TITLE
Override changes missing

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#86]
Hi!

The option to override changes on a shared folder is available just on web interface.

![override_changes](https://cloud.githubusercontent.com/assets/931642/6092322/448d2be4-aec0-11e4-85cb-ef3f8d6c957d.PNG)

**Comment by kozec** [comment]
Good point. Moving to TODO list :p

**Comment by kozec** [comment]
Just for record, ST-GTK now shows folder status as "Cluster out of sync" whenever Override Changes option is available.
![cff20b76-716c-469c-9ca8-e6b34ae5e9d5](https://cloud.githubusercontent.com/assets/1282500/6125636/93788686-b118-11e4-898e-70a98fcf2ae4.png)

Instead of button, option can be found in context menu (right-click anywhere in folder box)
![41b69d59-0e0b-4846-8bab-a2056b958abf](https://cloud.githubusercontent.com/assets/1282500/6125647/bf67770c-b118-11e4-9eed-0fb183f122ce.png)

**Comment by robsonsobral** [comment]
I've to confess that I found this function really confusing. It should be "Override remote changes" to make clear _where_ the changes will be override. But this is a topic for the Syncthing itself.

Thanks for your dedication, man!
