### ISSUE TITLE
failed to download syncthing

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing-gtk#97]
the gtk wrapper fails to accesses the downloaded syncthing. I already saw it downloading.

![screenshot](http://ibin.co/1thcKdaEAYWV)

Maybe it can not handle the German Umlaut Ü??

Cheers Lars

**Comment by kozec** [comment]
Yes, Ü in user name sounds like pretty good reason. I'll check where it gets converted incorrectly. As workaround, you can copy syncthing.exe anywhere, run it before ST-GTK and set path to executable in `UI Settings` -> `Advanced` afterwards.

**Comment by lkwg82** [comment]
thx, I had to fallback to btsync 2 because of that issue.

Manually copying is a maintenance no-go with more than one client. sry.

But next time I'll retry ;)

cheers Lars

**Comment by kozec** [comment]
Sorry, but this is simply OS limitation. Windows uses some random codepage instead of presenting your username & home folder related settings in unicode and then expects paths passed from application converted to this codepage in one place and presented in unicode on another. It's probably possible to dog out all places where it can possibly break, but it took me 3 hours just to fix downloader only to find out that it's not possible to write configuration to subfolder of `C:\Users\Jürgen\` ...

Related issue: http://bugs.python.org/issue13207

**Comment by lkwg82** [comment]
Sorry, thx anyway!

**Comment by vladipus** [comment]
Perhaps let user choose a custom path instead?
